//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf472.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHelloWorldService")]
    public interface IHelloWorldService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldService/SayHello", ReplyAction="http://tempuri.org/IHelloWorldService/SayHelloResponse")]
        string SayHello(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldService/SayHello", ReplyAction="http://tempuri.org/IHelloWorldService/SayHelloResponse")]
        System.Threading.Tasks.Task<string> SayHelloAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldService/SayFrom", ReplyAction="http://tempuri.org/IHelloWorldService/SayFromResponse")]
        string SayFrom();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldService/SayFrom", ReplyAction="http://tempuri.org/IHelloWorldService/SayFromResponse")]
        System.Threading.Tasks.Task<string> SayFromAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldService/GetDetailObject", ReplyAction="http://tempuri.org/IHelloWorldService/GetDetailObjectResponse")]
        Shared.Interfaces.DetailObject GetDetailObject(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldService/GetDetailObject", ReplyAction="http://tempuri.org/IHelloWorldService/GetDetailObjectResponse")]
        System.Threading.Tasks.Task<Shared.Interfaces.DetailObject> GetDetailObjectAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloWorldServiceChannel : Wpf472.ServiceReference1.IHelloWorldService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldServiceClient : System.ServiceModel.ClientBase<Wpf472.ServiceReference1.IHelloWorldService>, Wpf472.ServiceReference1.IHelloWorldService {
        
        public HelloWorldServiceClient() {
        }
        
        public HelloWorldServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWorldServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello(string name) {
            return base.Channel.SayHello(name);
        }
        
        public System.Threading.Tasks.Task<string> SayHelloAsync(string name) {
            return base.Channel.SayHelloAsync(name);
        }
        
        public string SayFrom() {
            return base.Channel.SayFrom();
        }
        
        public System.Threading.Tasks.Task<string> SayFromAsync() {
            return base.Channel.SayFromAsync();
        }
        
        public Shared.Interfaces.DetailObject GetDetailObject(string name) {
            return base.Channel.GetDetailObject(name);
        }
        
        public System.Threading.Tasks.Task<Shared.Interfaces.DetailObject> GetDetailObjectAsync(string name) {
            return base.Channel.GetDetailObjectAsync(name);
        }
    }
}
